import localFont from "next/font/local";
import "./globals.css";
import "../../public/css/vendor.css"
import "../../public/style.css"

const css = 
<>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />;
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" 
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossOrigin="anonymous"></link>;
<link rel="preconnect" href="https://fonts.googleapis.com"/>;
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin></link>;
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cormorant+Upright:wght@300;400;500;600;700&family=Jost:ital,wght@0,100..900;1,100..900&family=Lora:ital,wght@0,400..700;1,400..700&display=swap"></link>;
</>

// const estilo1 = {
//   backgroundimage: "url(images/banner-img2.png)";
//   backgroundsize: "cover",
//   backgroundrepeat: "no-repeat",
//   height: "90vh",
//   backgroundposition: "center",
//   height: "90vh",
// }

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        {css}
      </head>
      <body>
        <header id="header"> 
          <nav id="primary-header" className="navbar navbar-expand-lg py-3">
            <div className="container-lg">
              <a className="navbar-brand" href="#">
                <img src="/images/main-logo.png" className="logo img-fluid"/>
              </a>
              <button className="navbar-toggler border-0 d-flex d-lg-none order-3 p-2 shadow-none" type="button"
                data-bs-toggle="offcanvas" data-bs-target="#bdNavbar" aria-controls="bdNavbar" aria-expanded="false">
                <svg className="navbar-icon" width="60" height="60">
                  <use href="#navbar-icon"></use>
                </svg>
              </button>
              <div className="header-bottom offcanvas offcanvas-end" id="bdNavbar" aria-labelledby="bdNavbarOffcanvasLabel">
                <div className="offcanvas-header px-4 mt-3 ">
                  <button type="button" className="btn-close btn-close-black" data-bs-dismiss="offcanvas" aria-label="Close"
                    data-bs-target="#bdNavbar"></button>
                </div>
                <div className="offcanvas-body align-items-center justify-content-end">
                  <ul className="navbar-nav mb-2 mb-lg-0">
                    <li className="nav-item px-3 py-2 py-lg-0">
                      <a className="nav-link fw-semibold active p-0" aria-current="page" href="index.html">Home</a>
                    </li>
                    <li className="nav-item px-3 py-2 py-lg-0 dropdown">
                      <a className="nav-link fw-semibold p-0 dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                        aria-expanded="false">Serviços</a>
                      <ul className="dropdown-menu dropdown-menu-end animate slide mt-3 border-0 shadow">
                        <li><a href="services.html" className="dropdown-item">Services <span
                              className="badge bg-secondary text-black">Pro</span></a></li>
                        <li><a href="services-single.html" className="dropdown-item">Service-Details <span
                              className="badge bg-secondary text-black">Pro</span></a></li>
                      </ul>
                    </li>
                    <li className="nav-item px-3 py-2 py-lg-0">
                      <a className="nav-link fw-semibold p-0" href="contact.html">Contato</a>
                    </li>
                    <li className="nav-item px-3 py-2 py-lg-0">
                      <a className="nav-link p-0 fw-bold text-uppercase"
                        href="https://templatesjungle.gumroad.com/l/beauty-and-nail-salon-website-template"
                        target="_blank">LOGIN</a>
                    </li>
                    <li className="nav-item px-3 py-2 py-lg-0">
                      <a className="nav-link p-0 fw-bold text-uppercase"
                        href="https://templatesjungle.gumroad.com/l/beauty-and-nail-salon-website-template"
                        target="_blank">CADASTRE-SE</a>
                    </li>
                    <li className="nav-item search-dropdown py-2 py-lg-0 ms-3 ms-lg-5 dropdown">
                      <a className="nav-link p-0 search dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                        aria-expanded="false">
                        <svg className="search text-primary " width="24" height="24">
                          <use href="#search"></use>
                        </svg>
                      </a>
                      <ul className="dropdown-menu dropdown-menu-end animate slide mt-3 border-0 p-3 shadow">
                        <li className="position-relative d-flex align-items-center p-0">
                          <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                          <button className="btn btn-primary position-absolute end-0" type="submit">
                            <svg className="search" width="24" height="24">
                              <use href="#search"></use>
                            </svg>
                          </button>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </header>

        <section id="slider" >
          <div className="swiper slider "  >
            <div className="swiper-wrapper" style={{ backgroundImage: "url(/images/banner-img1.png)" }}>
              <div className="swiper-slide d-flex jarallax position-relative">
                <div className="banner-content text-center m-auto" data-aos="zoom-out">
                  <h2 className="banner-title display-2 fw-normal text-white mb-4">Embark on a journey of self-care and elegance
                  </h2>
                  <a href="appointment.html" className="btn btn-primary mt-3">Get an Appointment</a>
                </div>
              </div>
              <div className="swiper-slide d-flex jarallax position-relative" >
                {/* // style="background-image: url(images/banner-img1.png); background-size: cover; background-repeat: no-repeat; height: 90vh; background-position: center; height: 90vh;"> */}
                <div className="banner-content text-center m-auto" data-aos="zoom-out">
                  <h2 className="banner-title display-2 fw-normal text-white mb-4">Embark on a journey of self-care and elegance
                  </h2>
                  <a href="appointment.html" className="btn btn-primary mt-3">Get an Appointment</a>
                </div>
              </div>
              <div className="swiper-slide d-flex jarallax position-relative">
               {/* style="background-image: url(images/banner-img3.png); background-size: cover; background-repeat: no-repeat; height: 90vh; background-position: center; height: 90vh;" */}
                <div className="banner-content text-center m-auto" data-aos="zoom-out">
                  <h2 className="banner-title display-2 fw-normal text-white mb-4">Embark on a journey of self-care and elegance
                  </h2>
                  <a href="appointment.html" className="btn btn-primary mt-3">Get an Appointment</a>
                </div>
              </div>
            </div>
            <div className="position-absolute top-0 bottom-0 end-0 m-auto me-0 me-md-5 main-slider-button-next">
              <svg className="arrow-right light-color" width="60" height="60">
                <use href="#arrow-right"></use>
              </svg>
            </div>
            <div className="position-absolute top-0 bottom-0 start-0 m-auto ms-0 ms-md-5 main-slider-button-prev">
              <svg className="arrow-left light-color" width="60" height="60">
                <use href="#arrow-left"></use>
              </svg>
            </div>
          </div>
        </section>


        <script src="/js/jquery-1.11.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossOrigin="anonymous"></script>
        <script type="text/javascript" src="/js/plugins.js"></script>
        <script type="text/javascript" src="/js/script.js"></script>
        <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
      </body>
      
    </html>
  );
}
